// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package dependencyinjection

// Injectors from wire.go:

func InitializeServe(s string) Serve {
	message := NewMessage(s)
	chatroom := NewChatroom(message)
	serve := NewServe(chatroom)
	return serve
}
