// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package dependencyinjection

import (
	"github.com/charlieLin101274/golang-example-dependency-injection/example-1/config"
)

// Injectors from wire.go:

func InitializeServe(s string, cfg config.Config) Serve {
	message := NewMessage(s)
	chatroom := NewChatroom(message)
	serve := provideServe(cfg, chatroom)
	return serve
}

// wire.go:

func provideServe(cfg config.Config, c Chatroom) Serve {
	return NewServe(cfg.RoomName, c)
}
